/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkMetadataPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var LinkMetadataPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerMarkdownPostProcessor(this.processLinks.bind(this));
  }
  async processLinks(el, ctx) {
    el.querySelectorAll(".internal-link").forEach((linkEl) => {
      const linkPath = linkEl.getAttr("href");
      const file = this.app.metadataCache.getFirstLinkpathDest(linkPath, ctx.sourcePath);
      if (!file)
        return;
      const cache = this.app.metadataCache.getFileCache(file);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm)
        return;
      Object.entries(fm).forEach(([key, value]) => {
        if (typeof value === "string") {
          linkEl.addClass(`link-${key}-${value}`);
        }
        if (typeof value === "boolean" && value) {
          linkEl.addClass(`link-${key}-true`);
        }
        if (Array.isArray(value)) {
          const tags = value.map((t) => String(t).replace(/^#/, ""));
          tags.forEach((tag) => {
            linkEl.addClass(`link-${key}-${tag}`);
          });
        }
      });
    });
  }
};


/* nosourcemap */